name: 'Changelog emitter'
description: 'Github action for generating changelog out of pull requests'
inputs:
  branch:
    description: 'Pull request base branch (default: default branch)'
  title:
    description: 'Changelog title (default: YYYY/MM/DD)'
  prefix:
    description: 'Prefix for pull request title (default: "- ")'
  github_token:
    description: 'Github personal access token'
  owner:
    description: 'Owner or organization of repository'
  repo:
    description: 'Repository'
outputs:
  changelog:
    description: 'Changelog composed from PRs'
  isEmpty:
    description: 'Whether changelog is empty'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'align-left'
  color: blue
